---
# tasks file for roles/docker
- name: Install Docker apt key
    apt_key:
      url: "{{ docker_apt_key_url }}"
      state: present

- name: Add Docker Repository
    apt_repository:
      repo: "{{ docker_repo }}"
      state: present
      update_cache: "{{ docker_update_cache }}"

- name: Install Docker packages
    package:
      name: "{{ docker_packages }}"
      state: present
      update_cache: "{{ docker_update_cache }}"

